import Navbar from '@/components/Navbar'
import './globals.css'
import Sidebar from '@/components/Sidebar'

export const metadata = {
  title: 'SnippetHub',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`antialiased`}>
        <Navbar />
        <div className='md:flex justify-between relative'>
          {children}
          <Sidebar />
        </div>
      </body>
    </html>
  )
}
